CREATE TABLE task (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heading VARCHAR(50) NOT NULL,
    description VARCHAR NOT NULL,
    created_at TIMESTAMP NOT NULL,
    status varchar(20) NOT NULL,
    priority varchar(20) NOT NULL,
    author_id INT REFERENCES users(id)
);
CREATE TABLE comment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR,
    created_at TIMESTAMP NOT NULL,
    task_id INT REFERENCES task(id) ON DELETE CASCADE,
    author_id INT REFERENCES users(id)
);
CREATE TABLE user_task (
    user_id INT NOT NULL REFERENCES users(id),
    task_id INT NOT NULL REFERENCES task(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, task_id)
);